image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - apk update && apk add make

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - make build-all
  artifacts:
    paths:
      - build
    expire_in: 1 week
