image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - apk update && apk add make

after_script:
  - make clean

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - build
    expire_in: 1 week
